name: Build Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - 'firmware/**'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'firmware/**'

defaults:
  run:
    working-directory: firmware

env:
  build_target: NUCLEO_F412ZG
  build_profile: release
  filename: bcm-firmware.elf

jobs:
  build:
    container:
      image: ghcr.io/armmbed/mbed-os-env:mbed-os-6-latest

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Build Application
        run: |
          set -e
          mbed deploy
          mbed compile -t GCC_ARM -m $build_target --profile $build_profile
      -
        name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: $filename
          path: firmware/BUILD/${{ env.build_target }}/GCC_ARM-RELEASE/firmware.elf
