name: Build check

on:
  push:
    branches: [ main ]
    # Only execute when firmware changes are made
    paths: 'firmware/**'
  pull_request:
    branches: [ main ]
    paths: 'firmware/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow-dispatch:

defaults:
  working-directory: firmware

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      WORKING_DIR: firmware

    steps:
    - uses: actions/checkout@v2
    
    - name: arm-none-eabi-gcc
    - uses: fiam/arm-none-eabi-gcc@v1
      with: 
        release: '9-2019-q4' # The arm-none-eabi-gcc release to use.
    
    # - name: configure
    #   run: ./configure
      
    - name: Run build
      run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
